name: ci

on:
  push:
  pull_request:

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install fish -y

      - name: Test
        run: ./install.sh

      - name: chezmoi Data
        run: '"$HOME/.local/bin/chezmoi" data'

